const cleaningServices = {
  "Furnished apartment": [
    {
      _id: "CLA1BHK001",
      name: "1 BHK Cleaning - Classic",
      reviews: "4.80 (15K reviews)",
      price: 3199,
      details: "Includes 1 bedroom, 1 bathroom, 1 hall, 1 kitchen & 1 balcony",
      extras: "Basic cleaning, excludes terrace & paint marks removal",
      image: one,
      teamMembers: 3,
      duration: 2  //hr
    },
    {
      _id: "PRE1BHK002",
      name: "1 BHK Cleaning - Premium",
      reviews: "4.85 (12K reviews)",
      price: 4199,
      details:
        "Includes 1 bedroom, 1 bathroom, 1 hall, 1 kitchen & 1 balcony with deep cleaning",
      extras: "Includes upholstery cleaning, excludes paint marks removal",
      teamMembers: 3,
    },
    {
      _id: "PLA1BHK003",
      name: "1 BHK Cleaning - Platinum",
      reviews: "4.90 (10K reviews)",
      price: 5199,
      details:
        "Includes 1 bedroom, 1 bathroom, 1 hall, 1 kitchen & 1 balcony with premium deep cleaning",
      extras: "Includes upholstery and appliance cleaning",
      teamMembers: 3,
    },
    {
      name: "2 BHK Cleaning - Classic",
      reviews: "4.80 (41K reviews)",
      price: 3499,
      details:
        "Includes 2 bedrooms, 2 bathrooms, 1 hall, 1 kitchen & 2 balconies",
      extras: "Basic cleaning, excludes terrace & paint marks removal",
      image: twwo,
      teamMembers: 4,
    },
    {
      name: "2 BHK Cleaning - Premium",
      reviews: "4.85 (35K reviews)",
      price: 4499,
      details:
        "Includes 2 bedrooms, 2 bathrooms, 1 hall, 1 kitchen & 2 balconies with deep cleaning",
      extras: "Includes upholstery cleaning, excludes paint marks removal",
      teamMembers: 4,
    },
    {
      name: "2 BHK Cleaning - Platinum",
      reviews: "4.90 (30K reviews)",
      price: 5499,
      details:
        "Includes 2 bedrooms, 2 bathrooms, 1 hall, 1 kitchen & 2 balconies with premium deep cleaning",
      extras: "Includes upholstery and appliance cleaning",
      teamMembers: 4,
    },
    {
      name: "3 BHK Cleaning - Classic",
      reviews: "4.85 (10K reviews)",
      price: 3999,
      details:
        "Includes 3 bedrooms, 2 bathrooms, 1 hall, 1 kitchen & 1 balcony",
      extras: "Basic cleaning, excludes terrace & paint marks removal",
      image: three,
      teamMembers: 4,
    },
    {
      name: "3 BHK Cleaning - Premium",
      reviews: "4.88 (8K reviews)",
      price: 4999,
      details:
        "Includes 3 bedrooms, 2 bathrooms, 1 hall, 1 kitchen & 1 balcony with deep cleaning",
      extras: "Includes upholstery cleaning, excludes paint marks removal",
      teamMembers: 4,
    },
    {
      name: "3 BHK Cleaning - Platinum",
      reviews: "4.92 (7K reviews)",
      price: 5999,
      details:
        "Includes 3 bedrooms, 2 bathrooms, 1 hall, 1 kitchen & 1 balcony with premium deep cleaning",
      extras: "Includes upholstery and appliance cleaning",
      teamMembers: 4,
    },
    {
      name: "4 BHK Cleaning - Classic",
      reviews: "4.88 (8K reviews)",
      price: 4999,
      details:
        "Includes 4 bedrooms, 3 bathrooms, 1 hall, 1 kitchen & 1 balcony",
      extras: "Basic cleaning, excludes terrace & paint marks removal",
      image: four,
      teamMembers: 4,
    },
    {
      name: "4 BHK Cleaning - Premium",
      reviews: "4.90 (6K reviews)",
      price: 5999,
      details:
        "Includes 4 bedrooms, 3 bathrooms, 1 hall, 1 kitchen & 1 balcony with deep cleaning",
      extras: "Includes upholstery cleaning, excludes paint marks removal",
      teamMembers: 4,
    },
    {
      name: "4 BHK Cleaning - Platinum",
      reviews: "4.93 (5K reviews)",
      price: 6999,
      details:
        "Includes 4 bedrooms, 3 bathrooms, 1 hall, 1 kitchen & 1 balcony with premium deep cleaning",
      extras: "Includes upholstery and appliance cleaning",
      teamMembers: 4,
    },
    {
      name: "5+ BHK Cleaning - Classic",
      reviews: "4.85 (5K reviews)",
      price: 5999,
      details:
        "Includes 5+ bedrooms, 3+ bathrooms, 1 hall, 1 kitchen & 1 balcony",
      extras: "Basic cleaning, excludes terrace & paint marks removal",
      image: five,
      teamMembers: 4,
    },
    {
      name: "5+ BHK Cleaning - Premium",
      reviews: "4.90 (4K reviews)",
      price: 6999,
      details:
        "Includes 5+ bedrooms, 3+ bathrooms, 1 hall, 1 kitchen & 1 balcony with deep cleaning",
      extras: "Includes upholstery cleaning, excludes paint marks removal",
      teamMembers: 4,
    },
    {
      name: "5+ BHK Cleaning - Platinum",
      reviews: "4.95 (3K reviews)",
      price: 7999,
      details:
        "Includes 5+ bedrooms, 3+ bathrooms, 1 hall, 1 kitchen & 1 balcony with premium deep cleaning",
      extras: "Includes upholstery and appliance cleaning",
      teamMembers: 4,
    },
  ],
  "Unfurnished apartment": [
    {
      name: "1 BHK Cleaning - Classic",
      reviews: "4.75 (10K reviews)",
      price: 2799,
      details: "Includes 1 bedroom, 1 bathroom, 1 hall, 1 kitchen & 1 balcony",
      extras: "Basic cleaning, excludes paint marks removal",
      image: six,
      teamMembers: 2,
    },
    {
      name: "1 BHK Cleaning - Premium",
      reviews: "4.80 (8K reviews)",
      price: 3799,
      details:
        "Includes 1 bedroom, 1 bathroom, 1 hall, 1 kitchen & 1 balcony with deep cleaning",
      extras: "Includes thorough scrubbing, excludes paint marks removal",
      teamMembers: 2,
    },
    {
      name: "2 BHK Cleaning - Classic",
      reviews: "4.78 (12K reviews)",
      price: 3099,
      details:
        "Includes 2 bedrooms, 2 bathrooms, 1 hall, 1 kitchen & 2 balconies",
      extras: "Basic cleaning, excludes paint marks removal",
      image: seven,
      teamMembers: 3,
    },
    {
      name: "2 BHK Cleaning - Premium",
      reviews: "4.82 (10K reviews)",
      price: 4099,
      details:
        "Includes 2 bedrooms, 2 bathrooms, 1 hall, 1 kitchen & 2 balconies with deep cleaning",
      extras: "Includes thorough scrubbing, excludes paint marks removal",
      teamMembers: 3,
    },
    {
      name: "3 BHK Cleaning - Classic",
      reviews: "4.80 (9K reviews)",
      price: 3599,
      details:
        "Includes 3 bedrooms, 2 bathrooms, 1 hall, 1 kitchen & 1 balcony",
      extras: "Basic cleaning, excludes paint marks removal",
      image: eight,
      teamMembers: 3,
    },
    {
      name: "3 BHK Cleaning - Premium",
      reviews: "4.85 (7K reviews)",
      price: 4599,
      details:
        "Includes 3 bedrooms, 2 bathrooms, 1 hall, 1 kitchen & 1 balcony with deep cleaning",
      extras: "Includes thorough scrubbing, excludes paint marks removal",
      teamMembers: 3,
    },
    {
      name: "4 BHK Cleaning - Classic",
      reviews: "4.82 (6K reviews)",
      price: 4599,
      details:
        "Includes 4 bedrooms, 3 bathrooms, 1 hall, 1 kitchen & 1 balcony",
      extras: "Basic cleaning, excludes paint marks removal",
      image: nine,
      teamMembers: 4,
    },
    {
      name: "4 BHK Cleaning - Premium",
      reviews: "4.88 (5K reviews)",
      price: 5599,
      details:
        "Includes 4 bedrooms, 3 bathrooms, 1 hall, 1 kitchen & 1 balcony with deep cleaning",
      extras: "Includes thorough scrubbing, excludes paint marks removal",
      teamMembers: 3,
    },
    {
      name: "5+ BHK Cleaning - Classic",
      reviews: "4.80 (4K reviews)",
      price: 5599,
      details:
        "Includes 5+ bedrooms, 3+ bathrooms, 1 hall, 1 kitchen & 1 balcony",
      extras: "Basic cleaning, excludes paint marks removal",
      image: ten,
      teamMembers: 4,
    },
    {
      name: "5+ BHK Cleaning - Premium",
      reviews: "4.85 (3K reviews)",
      price: 6599,
      details:
        "Includes 5+ bedrooms, 3+ bathrooms, 1 hall, 1 kitchen & 1 balcony with deep cleaning",
      extras: "Includes thorough scrubbing, excludes paint marks removal",
      teamMembers: 4,
    },
  ],
  "Book by room": [
    {
      name: "Bedroom Cleaning - Unfurnished",
      reviews: "4.70 (8K reviews)",
      price: 999,
      details: "Cleaning of one empty bedroom",
      extras: "Excludes furniture cleaning",
      image: eleven,
      teamMembers: 1,
    },
    {
      name: "Bedroom Cleaning - Furnished",
      reviews: "4.75 (9K reviews)",
      price: 1299,
      details: "Cleaning of one furnished bedroom",
      extras: "Includes furniture wiping, excludes upholstery cleaning",
      teamMembers: 1,
    },
    {
      name: "Living Room Cleaning - Unfurnished",
      reviews: "4.65 (7K reviews)",
      price: 899,
      details: "Cleaning of one empty living room",
      extras: "Excludes furniture cleaning",
      image: tweleve,
      teamMembers: 1,
    },
    {
      name: "Living Room Cleaning - Furnished",
      reviews: "4.70 (8K reviews)",
      price: 1199,
      details: "Cleaning of one furnished living room",
      extras: "Includes furniture wiping, excludes upholstery cleaning",
      teamMembers: 1,
    },
    {
      name: "Kitchen Cleaning - Occupied Kitchen",
      reviews: "4.75 (10K reviews)",
      price: 1499,
      details: "Cleaning of occupied kitchen without appliances",
      extras: "Excludes appliance cleaning",
      image: thirteen,
      teamMembers: 1,
    },
    {
      name: "Kitchen Cleaning - Occupied Kitchen With Appliances",
      reviews: "4.80 (9K reviews)",
      price: 1999,
      details: "Cleaning of occupied kitchen with appliances",
      extras: "Includes basic appliance cleaning",
      teamMembers: 1,
    },
    {
      name: "Kitchen Cleaning - Empty Kitchen",
      reviews: "4.70 (6K reviews)",
      price: 999,
      details: "Cleaning of empty kitchen",
      extras: "Excludes appliance cleaning",
      teamMembers: 1,
    },
    {
      name: "Kitchen Cleaning - Empty Kitchen With Appliances",
      reviews: "4.75 (5K reviews)",
      price: 1499,
      details: "Cleaning of empty kitchen with appliances",
      extras: "Includes basic appliance cleaning",
      teamMembers: 1,
    },
    {
      name: "Bathroom Cleaning",
      reviews: "4.85 (12K reviews)",
      price: 799,
      details: "Cleaning of one bathroom",
      extras: "Includes sanitization",
      image: fourteen,
      teamMembers: 1,
    },
    {
      name: "Balcony Cleaning - Small (Upto 3 ft width)",
      reviews: "4.60 (5K reviews)",
      price: 499,
      details: "Cleaning of small balcony",
      extras: "Excludes plant cleaning",
      image: fifteen,
      teamMembers: 4,
    },
    {
      name: "Balcony Cleaning - Big (larger than 3 ft)",
      reviews: "4.65 (4K reviews)",
      price: 799,
      details: "Cleaning of large balcony",
      extras: "Excludes plant cleaning",
      teamMembers: 1,
    },
  ],
  "Furnished bungalow/duplex": [
    {
      name: "<1200 sqft Bungalow Cleaning - Classic",
      reviews: "4.80 (5K reviews)",
      price: 5999,
      details: "Includes full bungalow cleaning under 1200 sqft",
      extras: "Basic cleaning, excludes paint marks removal",
      image: sixteen,
      teamMembers: 2,
    },
    {
      name: "<1200 sqft Bungalow Cleaning - Premium",
      reviews: "4.85 (4K reviews)",
      price: 6999,
      details: "Includes deep cleaning for bungalow under 1200 sqft",
      extras: "Includes upholstery cleaning, excludes paint marks removal",
      teamMembers: 2,
    },
    {
      name: "<1200 sqft Bungalow Cleaning - Platinum",
      reviews: "4.90 (3K reviews)",
      price: 7999,
      details: "Includes premium deep cleaning for bungalow under 1200 sqft",
      extras: "Includes upholstery and appliance cleaning",
      teamMembers: 2,
    },
    {
      name: "1200-2000 sqft Bungalow Cleaning - Classic",
      reviews: "4.82 (4.5K reviews)",
      price: 6999,
      details: "Includes full bungalow cleaning for 1200-2000 sqft",
      extras: "Basic cleaning, excludes paint marks removal",
      image: seventeen,
      teamMembers: 3,
    },
    {
      name: "1200-2000 sqft Bungalow Cleaning - Premium",
      reviews: "4.87 (4K reviews)",
      price: 7999,
      details: "Includes deep cleaning for bungalow 1200-2000 sqft",
      extras: "Includes upholstery cleaning, excludes paint marks removal",
      teamMembers: 2,
    },
    {
      name: "1200-2000 sqft Bungalow Cleaning - Platinum",
      reviews: "4.92 (3.5K reviews)",
      price: 8999,
      details: "Includes premium deep cleaning for bungalow 1200-2000 sqft",
      extras: "Includes upholstery and appliance cleaning",
      teamMembers: 3,
    },
    {
      name: "2000-3000 sqft Bungalow Cleaning - Classic",
      reviews: "4.83 (4K reviews)",
      price: 7999,
      details: "Includes full bungalow cleaning for 2000-3000 sqft",
      extras: "Basic cleaning, excludes paint marks removal",
      image: eighteen,
      teamMembers: 4,
    },
    {
      name: "2000-3000 sqft Bungalow Cleaning - Premium",
      reviews: "4.88 (3.5K reviews)",
      price: 8999,
      details: "Includes deep cleaning for bungalow 2000-3000 sqft",
      extras: "Includes upholstery cleaning, excludes paint marks removal",
      teamMembers: 3,
    },
    {
      name: "2000-3000 sqft Bungalow Cleaning - Platinum",
      reviews: "4.93 (3K reviews)",
      price: 9999,
      details: "Includes premium deep cleaning for bungalow 2000-3000 sqft",
      extras: "Includes upholstery and appliance cleaning",
      teamMembers: 4,
    },
    {
      name: "3000-4000 sqft Bungalow Cleaning - Classic",
      reviews: "4.84 (3.5K reviews)",
      price: 9999,
      details: "Includes full bungalow cleaning for 3000-4000 sqft",
      extras: "Basic cleaning, excludes paint marks removal",
      image: ninteen,
      teamMembers: 4,
    },
    {
      name: "3000-4000 sqft Bungalow Cleaning - Premium",
      reviews: "4.89 (3K reviews)",
      price: 10999,
      details: "Includes deep cleaning for bungalow 3000-4000 sqft",
      extras: "Includes upholstery cleaning, excludes paint marks removal",
      teamMembers: 4,
    },
    {
      name: "3000-4000 sqft Bungalow Cleaning - Platinum",
      reviews: "4.94 (2.5K reviews)",
      price: 11999,
      details: "Includes premium deep cleaning for bungalow 3000-4000 sqft",
      extras: "Includes upholstery and appliance cleaning",
      teamMembers: 4,
    },
    {
      name: "4000-5000 sqft Bungalow Cleaning - Classic",
      reviews: "4.85 (3K reviews)",
      price: 11999,
      details: "Includes full bungalow cleaning for 4000-5000 sqft",
      extras: "Basic cleaning, excludes paint marks removal",
      image: twenty,
      teamMembers: 3,
    },
    {
      name: "4000-5000 sqft Bungalow Cleaning - Premium",
      reviews: "4.90 (2.5K reviews)",
      price: 12999,
      details: "Includes deep cleaning for bungalow 4000-5000 sqft",
      extras: "Includes upholstery cleaning, excludes paint marks removal",
      teamMembers: 4,
    },
    {
      name: "4000-5000 sqft Bungalow Cleaning - Platinum",
      reviews: "4.95 (2K reviews)",
      price: 13999,
      details: "Includes premium deep cleaning for bungalow 4000-5000 sqft",
      extras: "Includes upholstery and appliance cleaning",
      teamMembers: 2,
    },
    {
      name: "5000-6000 sqft Bungalow Cleaning - Classic",
      reviews: "4.86 (2.5K reviews)",
      price: 13999,
      details: "Includes full bungalow cleaning for 5000-6000 sqft",
      extras: "Basic cleaning, excludes paint marks removal",
      image: twentyone,
      teamMembers: 4,
    },
    {
      name: "5000-6000 sqft Bungalow Cleaning - Premium",
      reviews: "4.91 (2K reviews)",
      price: 14999,
      details: "Includes deep cleaning for bungalow 5000-6000 sqft",
      extras: "Includes upholstery cleaning, excludes paint marks removal",
      teamMembers: 3,
    },
    {
      name: "5000-6000 sqft Bungalow Cleaning - Platinum",
      reviews: "4.96 (1.5K reviews)",
      price: 15999,
      details: "Includes premium deep cleaning for bungalow 5000-6000 sqft",
      extras: "Includes upholstery and appliance cleaning",
      teamMembers: 3,
    },
    {
      name: "6000-7000 sqft Bungalow Cleaning - Classic",
      reviews: "4.85 (2K reviews)",
      price: 15999,
      details: "Includes full bungalow cleaning for 6000-7000 sqft",
      extras: "Basic cleaning, excludes paint marks removal",
      image: twentytwo,
      teamMembers: 4,
    },
    {
      name: "6000-7000 sqft Bungalow Cleaning - Premium",
      reviews: "4.90 (1.5K reviews)",
      price: 17999,
      details: "Includes deep cleaning for bungalow 6000-7000 sqft",
      extras: "Includes upholstery cleaning, excludes paint marks removal",
      teamMembers: 4,
    },
    {
      name: "6000-7000 sqft Bungalow Cleaning - Platinum",
      reviews: "4.95 (1K reviews)",
      price: 19999,
      details: "Includes premium deep cleaning for bungalow 6000-7000 sqft",
      extras: "Includes upholstery and appliance cleaning",
      teamMembers: 4,
    },
  ],
  "Unfurnished bungalow/duplex": [
    {
      name: "<1200 sqft Bungalow Cleaning - Classic",
      reviews: "4.75 (4K reviews)",
      price: 5499,
      details: "Includes full bungalow cleaning under 1200 sqft",
      extras: "Basic cleaning, excludes paint marks removal",
      image: twentythree,
      teamMembers: 4,
    },
    {
      name: "<1200 sqft Bungalow Cleaning - Premium",
      reviews: "4.80 (3K reviews)",
      price: 6499,
      details: "Includes deep cleaning for bungalow under 1200 sqft",
      extras: "Includes thorough scrubbing, excludes paint marks removal",
      teamMembers: 4,
    },
    {
      name: "1200-2000 sqft Bungalow Cleaning - Classic",
      reviews: "4.77 (3.5K reviews)",
      price: 6499,
      details: "Includes full bungalow cleaning for 1200-2000 sqft",
      extras: "Basic cleaning, excludes paint marks removal",
      image: twentyfour,
      teamMembers: 4,
    },
    {
      name: "1200-2000 sqft Bungalow Cleaning - Premium",
      reviews: "4.82 (3K reviews)",
      price: 7499,
      details: "Includes deep cleaning for bungalow 1200-2000 sqft",
      extras: "Includes thorough scrubbing, excludes paint marks removal",
      teamMembers: 4,
    },
    {
      name: "2000-3000 sqft Bungalow Cleaning - Classic",
      reviews: "4.78 (3K reviews)",
      price: 7499,
      details: "Includes full bungalow cleaning for 2000-3000 sqft",
      extras: "Basic cleaning, excludes paint marks removal",
      image: twentyfive,
      teamMembers: 4,
    },
    {
      name: "2000-3000 sqft Bungalow Cleaning - Premium",
      reviews: "4.83 (2.5K reviews)",
      price: 8499,
      details: "Includes deep cleaning for bungalow 2000-3000 sqft",
      extras: "Includes thorough scrubbing, excludes paint marks removal",
      teamMembers: 4,
    },
    {
      name: "3000-4000 sqft Bungalow Cleaning - Classic",
      reviews: "4.79 (2.5K reviews)",
      price: 9499,
      details: "Includes full bungalow cleaning for 3000-4000 sqft",
      extras: "Basic cleaning, excludes paint marks removal",
      image: twentysix,
      teamMembers: 4,
    },
    {
      name: "3000-4000 sqft Bungalow Cleaning - Premium",
      reviews: "4.84 (2K reviews)",
      price: 10499,
      details: "Includes deep cleaning for bungalow 3000-4000 sqft",
      extras: "Includes thorough scrubbing, excludes paint marks removal",
      teamMembers: 4,
    },
    {
      name: "4000-5000 sqft Bungalow Cleaning - Classic",
      reviews: "4.80 (2K reviews)",
      price: 11499,
      details: "Includes full bungalow cleaning for 4000-5000 sqft",
      extras: "Basic cleaning, excludes paint marks removal",
      image: twentyseven,
      teamMembers: 4,
    },
    {
      name: "4000-5000 sqft Bungalow Cleaning - Premium",
      reviews: "4.85 (1.5K reviews)",
      price: 12499,
      details: "Includes deep cleaning for bungalow 4000-5000 sqft",
      extras: "Includes thorough scrubbing, excludes paint marks removal",
      teamMembers: 3,
    },
    {
      name: "5000-6000 sqft Bungalow Cleaning - Classic",
      reviews: "4.81 (1.5K reviews)",
      price: 13499,
      details: "Includes full bungalow cleaning for 5000-6000 sqft",
      extras: "Basic cleaning, excludes paint marks removal",
      image: twentyeight,
      teamMembers: 3,
    },
    {
      name: "5000-6000 sqft Bungalow Cleaning - Premium",
      reviews: "4.86 (1K reviews)",
      price: 14499,
      details: "Includes deep cleaning for bungalow 5000-6000 sqft",
      extras: "Includes thorough scrubbing, excludes paint marks removal",
      teamMembers: 3,
    },
    {
      name: "6000-7000 sqft Bungalow Cleaning - Classic",
      reviews: "4.80 (1K reviews)",
      price: 14999,
      details: "Includes full bungalow cleaning for 6000-7000 sqft",
      extras: "Basic cleaning, excludes paint marks removal",
      image: twentyeight,
      teamMembers: 4,
    },
    {
      name: "6000-7000 sqft Bungalow Cleaning - Premium",
      reviews: "4.85 (800 reviews)",
      price: 16999,
      details: "Includes deep cleaning for bungalow 6000-7000 sqft",
      extras: "Includes thorough scrubbing, excludes paint marks removal",
      teamMembers: 2,
    },
  ],
  "Mini services": [
    {
      name: "Kitchen Appliances Cleaning - Chimney",
      reviews: "4.70 (6K reviews)",
      price: 799,
      details: "Deep cleaning of kitchen chimney",
      extras: "Excludes external pipe cleaning",
      image: twentynine,
      teamMembers: 1,
      duration: 1.5
    },
    {
      name: "Kitchen Appliances Cleaning - Microwave",
      reviews: "4.65 (5K reviews)",
      price: 499,
      details: "Cleaning of microwave interior and exterior",
      extras: "Includes sanitization",
      teamMembers: 1,
      duration: 0.5
    },
    {
      name: "Kitchen Appliances Cleaning - Stove",
      reviews: "4.70 (4K reviews)",
      price: 599,
      details: "Cleaning of gas stove",
      extras: "Includes burner cleaning",
      teamMembers: 1,
      duration: 0.75
    },
    {
      name: "Kitchen Appliances Cleaning - Single Door Fridge",
      reviews: "4.75 (3K reviews)",
      price: 699,
      details: "Cleaning of single door fridge",
      extras: "Includes interior and exterior cleaning",
      teamMembers: 1,
      duration: 0.75
    },
    {
      name: "Kitchen Appliances Cleaning - Double Door Fridge",
      reviews: "4.80 (2K reviews)",
      price: 999,
      details: "Cleaning of double door fridge",
      extras: "Includes interior and exterior cleaning",
      teamMembers: 1,
      duration: 1.5
    },
    {
      name: "Sofa & Upholstery Wet Shampooing - Sofa (5 seats)",
      reviews: "4.85 (5K reviews)",
      price: 1499,
      details: "Wet shampooing of 5-seat sofa",
      extras: "Includes stain removal",
      image: thirty,
      teamMembers: 1,
      duration: 1.5
    },
    {
      name: "Sofa & Upholstery Wet Shampooing - Carpet (upto 25 sqft)",
      reviews: "4.80 (4K reviews)",
      price: 999,
      details: "Wet shampooing of carpet up to 25 sqft",
      extras: "Includes stain removal",
      teamMembers: 1,
      duration: 1.0
    },
    {
      name: "Sofa & Upholstery Wet Shampooing - Cushion Chair",
      reviews: "4.75 (3K reviews)",
      price: 499,
      details: "Wet shampooing of one cushion chair",
      extras: "Includes stain removal",
      teamMembers: 1,
      duration: 0.5
    },
    {
      name: "Sofa & Upholstery Wet Shampooing - Mattress",
      reviews: "4.80 (4K reviews)",
      price: 1299,
      details: "Wet shampooing of one mattress",
      extras: "Includes stain removal",
      teamMembers: 1,
      duration: 1.0
    },
    {
      name: "Utensil Removal & Placement",
      reviews: "4.60 (2K reviews)",
      price: 399,
      details: "Removal and placement of utensils",
      extras: "Excludes cleaning of utensils",
      image: thirtytwo,
      teamMembers: 1,
      duration: 1.0
    },
    {
      name: "Cabinet Cleaning (Upto 2)",
      reviews: "4.65 (3K reviews)",
      price: 599,
      details: "Cleaning of up to 2 cabinets",
      extras: "Includes interior and exterior cleaning",
      image: thirtythree,
      teamMembers: 1,
      duration: 0.75
    },
    {
      name: "Furniture Wet Wiping",
      reviews: "4.70 (3K reviews)",
      price: 799,
      details: "Wet wiping of furniture surfaces",
      extras: "Excludes upholstery cleaning",
      image: thirtyfour,
      teamMembers: 1,
      duration: 1.0
    },
    {
      name: "Ceiling Dusting & Cobweb Removal",
      reviews: "4.75 (4K reviews)",
      price: 499,
      details: "Dusting and cobweb removal from ceilings",
      extras: "Excludes high ceiling areas above 12 ft",
      image: thirtyfive,
      teamMembers: 1,
      duration: 0.75
    },
  ],
};